// Pure: build the .env.local body. Secrets only. Session secret is injected
// by the caller so this stays deterministic and testable.
export function renderEnv(values, sessionSecret) {
  const lines = ["# Generated by `npm run init`. Secrets only — never commit this file."];
  if (values.mode === "password" && values.accessPassword) {
    lines.push(`ACCESS_PASSWORD=${values.accessPassword}`);
  }
  if (values.mode === "google") {
    if (values.googleClientId) lines.push(`GOOGLE_CLIENT_ID=${values.googleClientId}`);
    if (values.googleClientSecret) lines.push(`GOOGLE_CLIENT_SECRET=${values.googleClientSecret}`);
  }
  if (values.resendKey) lines.push(`RESEND_EMAIL_TRACKING_API_KEY=${values.resendKey}`);
  lines.push(`AUTH_SESSION_SECRET=${sessionSecret}`);
  return lines.join("\n") + "\n";
}
